theme: jekyll-theme-cayman
title: International Workshop on DevOps for Sustainability (DevOpsSustain 2025)
description: To be co-located with ACM International Conference on the Foundations of Software Engineering (FSE)
github:
  is_project_page: false
