theme: jekyll-theme-cayman
title: WOSP-C 2024
description: International Workshop on DevOps for Sustainability (DevOpsSustain)<br \>ACM International Conference on the Foundations of Software Engineering (FSE)
github:
  is_project_page: false
