theme: jekyll-theme-cayman
title: WOSP-C 2023
description: Workshop on Challenges in Performance Methods for Software Development<br \>International Conference on Performance Engineering (ICPE)
github:
  is_project_page: false
